name: Test Continuous Integration and deployment

on:
  push:
    branches:
        -master
  
jobs:
  build:
    runs-on: ubuntu latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v2

      - name: dotnet version
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore dependancies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

