name: Test Continuous Integration and deployment

on:
  push:
    branches: [ master ]
  
jobs:
      # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    
    steps:
       - uses: actions/checkout@v2

       - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1
            with:
             dotnet-version: 5.0

       - name: Restore dependancies
          run: dotnet restore

       - name: Build app
          run: dotnet build -c Release --no-restore

